{{/*
Config Maps list template.
This template takes an array of values:
- the top context
- the config maps list

# Example values.yaml
configmaps:
- name: myconfigmap
  data: {}
*/}}
{{define "common.configmaps" -}}
{{- $args     := compact  . -}}
{{- $top      := first    $args -}}
{{- $args     := rest     $args  -}}
{{- range $configMaps := $args -}}
{{- range $configMap := $configMaps -}}
{{- include "common.configmap" (list $top $configMap) -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{/*
Config Map template.
This template takes an array of values:
- the top context
- the config map value
- optional template name of the overrides

# Example values.yaml
configmap:
  name: myconfigmap
  data: {}
*/}}
{{- define "common.configmap" -}}
{{- $args     := compact  . -}}
{{- $top      := first    $args -}}
{{- $args     := rest     $args -}}
{{- if typeIs "string" (last $args) -}}
{{- template "common.util.merge" (append . "common.configmap.tpl") -}}
{{- else -}}
{{- template "common.configmap.tpl" . -}}
{{- end -}}
{{- end -}}

{{define "common.configmap.tpl" -}}
{{- $args     := compact  . -}}
{{- $top      := first    $args -}}
{{- $args     := rest     $args  -}}
{{- $data     := dict -}}
{{- range $values := $args -}}
{{- $data      = $data | merge $values -}}
{{- end -}}
apiVersion: v1
kind: ConfigMap
metadata:
  {{- include "common.metadata" . | nindent 2 }}
{{- with $data.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end -}}
