{{/*
Deployment template.
This template takes an array of values:
- the top context
- the deployment values
- optional template name of the overrides

# Example values.yaml
deployment:
  name: mydeployment   # Optional. Will be prefixed with .Chart.Name
  labels: {}
  selectors: {}
  annotations: {}
  checksums: []       # File names relative to templates folder.
  replicaCount: 1     # Ignored if horizontalPodAutoscaler is defined
  revisionHistoryLimit: 10
  imagePullSecrets: {}
  podSecurityContext: {}
  nodeSelector: {}
  affinity: {}
  tollerations: []
*/}}
{{- define "common.deployment" -}}
{{- $args     := compact  . -}}
{{- $top      := first    $args -}}
{{- $args     := rest     $args -}}
{{- if typeIs "string" (last $args) -}}
{{- template "common.util.merge" (append . "common.deployment.tpl") -}}
{{- else -}}
{{- template "common.deployment.tpl" . -}}
{{- end -}}
{{- end -}}

{{- define "common.deployment.tpl" -}}
{{- $args     := compact  . -}}
{{- $top      := first    $args -}}
{{- $args     := rest     $args | default (list $top.Values) -}}
{{- $deployment := dict -}}
{{- range $values := $args -}}
{{- $deployment = $deployment | merge $values -}}
{{- end -}}
{{- $hpa := $deployment.horizontalPodAutoscaler | default (dict) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- include "common.metadata" . | nindent 2 }}
spec:
  {{- if not $hpa.enabled }}
  replicas: {{ $deployment.replicaCount | default 1 }}
  {{- end }}
  {{- with $deployment.revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  {{- with $deployment.strategy }}
  strategy:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common.metadata.selectors" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.metadata.selectors" . | nindent 8 }}
    spec:
      {{- include "common.pod.spec" . | nindent 6 }}
{{- end -}}
