{{/*
Service template.
This template takes an array of values:
- the top context
- the service values
- optional template name of the overrides

# Example values.yaml
service:
  type: ClusterIP
  name: service
  ports: []
  # - port: 1234
  #   targetPort: 1234
  #   protocol: tcp
  #   name: http
  sessionAffinity: ClientIP
  sessionAffinityConfig: {}
*/}}
{{- define "common.service" -}}
{{- $args     := compact  . -}}
{{- $top      := first    $args -}}
{{- $args     := rest     $args -}}
{{- if typeIs "string" (last $args) -}}
{{- template "common.util.merge" (append . "common.service.tpl") -}}
{{- else -}}
{{- template "common.service.tpl" . -}}
{{- end -}}
{{- end -}}

{{- define "common.service.tpl" -}}
{{- $args     := compact  . -}}
{{- $top      := first    $args -}}
{{- $args     := rest     $args  -}}
{{- $service  := dict -}}
{{- range $values := $args -}}
{{- $service   = $service | merge $values -}}
{{- end -}}
apiVersion: v1
kind: Service
metadata:
  {{- include "common.metadata" . | nindent 2 }}
spec:
  type: {{ $service.type | quote }}
  {{- with $service.ClusterIP }}
  ClusterIP: {{ . | quote }}
  {{- end }}
  {{- if eq $service.type "LoadBalancer" }}
  {{- with $service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . | quote }}
  {{- end }}
  {{- with $service.loadBalancerIP }}
  loadBalancerIP: {{ . | quote }}
  {{- end }}
  {{- with $service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{ toYaml . | nindent 2 }}
  {{- end }}
  {{- with $service.healthCheckNodePort }}
  healthCheckNodePort: {{ . }}
  {{- end }}
  {{- else if eq $service.type "NodePort" }}
  {{- with $service.nodePort }}
  nodePort: {{ . }}
  {{- end }}
  {{- else if eq $service.type "ExternalName" }}
  {{- with $service.externalName }}
  externalName: {{ . | quote }}
  {{- end }}
  {{- end }}
  {{- with $service.externalIPs }}
  externalIPs:
  {{ toYaml . | nindent 2 }}
  {{- end }}
  ports:
  {{- range $port := $service.ports }}
  - port: {{ $port.port }}
    targetPort: {{ $port.targetPort }}
    protocol: {{ $port.protocol | default "tcp" | quote }}
    {{- with $port.name }}
    name: {{ . | quote }}
    {{- end }}
  {{- end }}
  {{- with $service.sessionAffinity }}
  sessionAffinity: {{ . | quote }}
  {{- end }}
  {{- with $service.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- if not (eq $service.type "ExternalName") }}
  selector:
    {{- include "common.metadata.selectors" (list $top $service) | nindent 4 }}
  {{- end }}
{{- end -}}
