{{/*
Service Account template.
This template takes an array of values:
- the top context
- the service account values
- optional template name of the overrides

# Example values.yaml
serviceAccount:
  create: yes
  # name: # defaults to common.fullname
  labels: {}
  annotations: {}
  automountServiceAccountToken: yes
  imagePullSecrets: []
  secrets: []
*/}}
{{- define "common.serviceaccount" -}}
{{- $args     := compact  . -}}
{{- $top      := first    $args -}}
{{- $args     := rest     $args -}}
{{- if typeIs "string" (last $args) -}}
{{- template "common.util.merge" (append . "common.serviceaccount.tpl") -}}
{{- else -}}
{{- template "common.serviceaccount.tpl" . -}}
{{- end -}}
{{- end -}}

{{- define "common.serviceaccount.tpl" -}}
{{- $args     := compact  . -}}
{{- $top      := first    $args -}}
{{- $args     := rest     $args  -}}
{{- $serviceAccount := dict -}}
{{- range $values := $args -}}
{{- $serviceAccount = $serviceAccount | merge $values -}}
{{- end -}}
{{- if $serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- include "common.metadata" . | nindent 2 }}
{{- with $serviceAccount.automountServiceAccountToken }}
automountServiceAccountToken: {{ . }}
{{- end }}
{{- with $serviceAccount.imagePullSecrets }}
imagePullSecrets:
{{- toYaml . | nindent 0 }}
{{- end }}
{{- with $serviceAccount.secrets }}
secrets:
{{- toYaml . | nindent 0 }}
{{- end }}
{{- end }}
{{- end -}}
