{{/*
StaefulSet template.
This template takes an array of values:
- the top context
- the stateful set values
- optional template name of the overrides

# Example values.yaml
statefulset:
  name: mystatefulset # Optional. Will be prefixed with .Chart.Name
  labels: {}
  selectors: {}
  annotations: {}
  checksums: []       # File names relative to templates folder.
  replicaCount: 1     # Ignored if horizontalPodAutoscaler is defined
  podManagementPolicy: OrderedReady
  revisionHistoryLimit: 10
  serviceName: myservice
  updateStrategy: {}
  imagePullSecrets: {}
  podSecurityContext: {}
  nodeSelector: {}
  affinity: {}
  tollerations: []
*/}}
{{- define "common.statefulset" -}}
{{- $args     := compact  . -}}
{{- $top      := first    $args -}}
{{- $args     := rest     $args -}}
{{- if typeIs "string" (last $args) -}}
{{- template "common.util.merge" (append . "common.statefulset.tpl") -}}
{{- else -}}
{{- template "common.statefulset.tpl" . -}}
{{- end -}}
{{- end -}}

{{- define "common.statefulset.tpl" -}}
{{- $args     := compact  . -}}
{{- $top      := first    $args -}}
{{- $args     := rest     $args | default (list $top.Values) -}}
{{- $statefulset := dict -}}
{{- range $values := $args -}}
{{- $statefulset = $statefulset | merge $values -}}
{{- end -}}
{{- $hpa := $statefulset.horizontalPodAutoscaler | default (dict) -}}
{{- $fullname := include "common.fullname" $top -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  {{- include "common.metadata" . | nindent 2 }}
spec:
  {{- if not $hpa.enabled }}
  replicas: {{ $statefulset.replicaCount | default 1 }}
  {{- end }}
  serviceName: {{ list $fullname $statefulset.serviceName | compact | join "-" | quote }}
  {{- with $statefulset.podManagementPolicy }}
  podManagementPolicy: {{ . | quote }}
  {{- end }}
  {{- with $statefulset.revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  {{- with $statefulset.updateStrategy }}
  updateStrategy:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common.metadata.selectors" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.metadata.selectors" . | nindent 8 }}
    spec:
      {{- include "common.pod.spec" . | nindent 6 }}
  {{- with $statefulset.volumeClaimTemplates }}
  volumeClaimTemplates:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
