{{- /* Daemon Set */ -}}
{{- include "common.daemonset" (list . .Values "example.daemonset") -}}

{{- /* Daemon Set overrides*/ -}}
{{- define "example.daemonset" -}}
spec:
  template:
    spec:
      containers:
      - {{- include "common.container" (list . .Values "example.daemonset.container") | nindent 8 }}
      volumes:
      - name: nginx-html
        configMap:
          name: {{ include "common.fullname" . }}-html
{{- end -}}

{{- /* Container overrides */ -}}
{{- define "example.daemonset.container" -}}
ports:
- name: http
  containerPort: 80
  protocol: TCP
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
volumeMounts:
- mountPath: /usr/share/nginx/html
  name: nginx-html
{{- end -}}
