{{- /* Deployment */ -}}
{{- include "common.deployment" (list . .Values "example.deployment") -}}

{{- /* Deplyment overrides*/ -}}
{{- define "example.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{- include "common.container" (list . .Values "example.deployment.container") | nindent 8 }}
      volumes:
      - name: nginx-html
        configMap:
          name: {{ include "common.fullname" . }}-html
{{- end -}}

{{- /* Container overrides */ -}}
{{- define "example.deployment.container" -}}
ports:
- name: http
  containerPort: 80
  protocol: TCP
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
volumeMounts:
- mountPath: /usr/share/nginx/html
  name: nginx-html
{{- end -}}
