{{- /* Stateful Set */ -}}
{{- include "common.statefulset" (list . .Values "example.statefulset") -}}

{{- /* Stateful Set overrides*/ -}}
{{- define "example.statefulset" -}}
spec:
  template:
    spec:
      containers:
      - {{- include "common.container" (list . .Values "example.statefulset.container") | nindent 8 }}
      volumes:
      - name: nginx-html
        configMap:
          name: {{ include "common.fullname" . }}-html
{{- end -}}

{{- /* Container overrides */ -}}
{{- define "example.statefulset.container" -}}
ports:
- name: http
  containerPort: 80
  protocol: TCP
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
volumeMounts:
- mountPath: /usr/share/nginx/html
  name: nginx-html
{{- end -}}
